services:
  db:
    image: mariadb:lts
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - pdc

  wordpress:
    depends_on:
      - db
    image: ${WP_IMAGE}
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: '1'
      PDC_POD_API_BASE_URL: http://pdc-mock-api:8080
    volumes:
      - wordpress_data:/var/www/html
      - ../:/var/www/html/wp-content/plugins/pdc-pod
    ports:
      - '${WORDPRESS_PORT:-8000}:80'
    extra_hosts: ['host.docker.internal:host-gateway']
    networks:
      - pdc

  wpcli:
    image: 'wordpress:cli-php${PHP_VERSION:-8.2}'
    user: "33:33"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      HOME: /var/www/html
      WP_CLI_PACKAGES_DIR_PATH: /var/www/html/.wp-cli/packages
      COMPOSER_HOME: /var/www/html/.composer
    volumes:
      - wordpress_data:/var/www/html
      - ../:/var/www/html/wp-content/plugins/pdc-pod
    working_dir: /var/www/html
    networks:
      - pdc
    depends_on:
      wordpress:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  db_data:
  wordpress_data:

networks:
  pdc:
    name: pdc